root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
include_dir = ["internal"]
include_file = ["main.go"]
exclude_dir = ["src", "tmp", "vendor", "node_modules", "config"]
exclude_unchanged = true
follow_symlink = true
delay = 300 # ms
stop_on_error = true
send_interrupt = true
# Delay after sending Interrupt signal
kill_delay = 500 # nanosecond
poll = true
# rerun = true

[log]
time = true
# # Only show main log (silences watcher, build, runner)
# main_only = false
# # silence all logs produced by air
# silent = false

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
# clear_on_rebuild = true
keep_scroll = true

[proxy]
# Enable live-reloading on the browser.
enabled = true
proxy_port = 8090
app_port = 8080
