root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_dir = ["internal"]
  include_file = ["main.go"]
  exclude_dir = ["src", "tmp", "vendor", "node_modules"]
  poll = true
  rerun = true

[log]
  time = true

[proxy]
# Enable live-reloading on the browser.
enabled = true
proxy_port = 8090
app_port = 8080
